### ISSUE TITLE
Add debugging flag

### ISSUE THREAD

**Issue by Revolucent** [Prosumma/CoreDataQueryInterface#28]
Add a launch flag along the lines of `-com.apple.CoreData.SQLDebug`, but instead of printing out the SQL (for which you can already use the aforementioned tag), this will print out any generated predicates, and possibly other useful information.

`-com.prosumma.CoreDataQueryInterface.Debug`, perhaps?

**Comment by Revolucent** [comment]
Closed in d2a2a6651f29235b9397471770d7252fba9f3481

**Comment by patgoley** [comment]
@Revolucent Just looked over this for fun. One thing to note, and this probably doesn't matter, but `print` only logs to the debug console while `NSLog` also prints to the device console. I can't think of a reason that someone would ship a production build with the logging enabled but if they did, they wouldn't be able to read it from the device console or at all. Just wanted to make sure we intentionally opted for that limitation.

I am one for splitting hairs obviously :) I just feel like if you opt for the logging flag you should get the full service. But probably no one cares.

**Comment by Revolucent** [comment]
> I am one for splitting hairs obviously.

Me, too. I think we just tend to split different hairs. But in this case, I think I will switch to `NSLog`. When Swift was released, people simply stopped using `NSLog`. All of the examples used `print` (well `println`). I simply assumed it was Swift's `NSLog` and left it at that. I never even noticed that it didn't print the date. The truth is I never thought too deeply about it, so good to know the distinction.

What I'm surprised _didn't_ leap out at you was this brain dead code:

``` swift
NSProcossInfo().arguments.filter{ $0 == "-com.prosumma.CoreDataQueryInterface.Debug" }.count > 0
```

It should have been:

``` swift
NSProcessInfo().arguments.contains("-com.prosumma.CoreDataQueryInterface.Debug")
```

I'll make the changes.
