### ISSUE TITLE
More unit test coverage

### ISSUE THREAD

**Issue by Revolucent** [Prosumma/CoreDataQueryInterface#29]
While @patgoley and I were working on typesafe attributes for version 4, it became clear to me that my unit test coverage was not sufficient. For instance, there were no tests that covered scenarios like `ANY employees.lastName == 'Goley'`, which led @patgoley to make some incorrect assumptions about how to-many attributes need to work. Had such a unit test failed, it would have led to less wasted effort.

**Comment by patgoley** [comment]
Started improving our test coverage on the [improve-tests](https://github.com/patgoley/CoreDataQueryInterface/tree/improve-tests) branch on my fork. Basically just enabled code coverage and having started filling in the gaps. The scenario in the issue above has also been addressed. Still more to come.

**Comment by Revolucent** [comment]
I think you're more in a hurry to get v4.0 out than I am. :)

**Comment by patgoley** [comment]
What else am I supposed to do with my Monday night? Highlights include finding out that we can't > or < against nil because that's an invalid predicate (throws NSInvalidArgumentException), so I've removed the Null variants of those functions. And that amounts to one more kind of exception that can be avoided by using CDQI, which is cool. Maybe one day we can even get rid of the `try` because it's so safe and all :)

Other than that everything has been working as expected. It's at 90% coverage now on my branch. The tests are stupidly simple to write it's just a matter of covering everything. I'll do a few more tomorrow and submit a PR.

**Comment by Revolucent** [comment]
> What else am I supposed to do with my Monday night? Highlights include finding out that we can't > or < against nil because that's an invalid predicate (throws NSInvalidArgumentException), so I've removed the Null variants of those functions.

Yep. I noticed that myself and had been intending to remove them, but you beat me to it. Thanks for all the help.

**Comment by Revolucent** [comment]
I've been thinking about removing `try` for some time, but I'm going to leave it in for v4.0. Pretty much 100% of errors that occur in Core Data queries are "programmer errors", i.e., they are the kind of thing that gets caught during the development cycle. What kind of "rescue" is possible from the failure of a Core Data query? Not much, really. My production code that uses CDQI is actually peppered with the usually unsafe `try!`. This is a sign that the calls are not actually unsafe.

I intend v5.0 to be a partial rewrite to take advantage of new features in the Swift language. I think `try` will go out the window in that version.

**Comment by patgoley** [comment]
I think that CDQI can eliminate all of the errors associated with invalid keypaths, invalid type comparisons, and invalid operators/functions for particular types. 

The one error I could see being more difficult to eliminate statically is that the type provided for a query (i.e. Employee) _actually exists_ in the persistent store attached to the context being queried. It could be done, but CDQI would have to involve itself in the creation and providing of the context in relation to the store/model which is probably beyond the scope of the framework.

But that kind of error is so rare and you really fucked up if it happens so it might be reasonable to internally handle the `try`. 

It would make for a sick motto: Core Data, without `try` - ing. Just saying... ;)

**Comment by Revolucent** [comment]
> But that kind of error is so rare and you really fucked up if it happens so it might be reasonable to internally handle the `try`.

Well, that's exactly my point. This is the kind of error you catch during the development cycle. What would you do with such an error at runtime in a shipping app?

``` swift
do {
    try moc.from(Employee).blah()
} catch {
    // What realistically could go here if Employee doesn't exist?
}
```

4.0 is a major release. It doesn't _have_ to be backwards compatible with 3.x. You know what, let's remove `try` in 4.0. However, not to disappoint you, but I'll take this one. In fact, I'm going to do it right now.

**Comment by patgoley** [comment]
`fatalError('you fucked up, badly')`

Edit: Anything @noreturn that informs the developer of their mistake.

**Comment by Revolucent** [comment]
@patgoley 

OK, `try` is gone, and that code has been pushed to the `release-4.0` branch. If you want to merge/rebase, that's great, or I can just take out the `try!` clauses when I merge your branch.

**Comment by patgoley** [comment]
@Revolucent A bold move, I like it. We should try to figure out which errors are still possible and document them. One other thing I just thought of is that there might be invalid attribute types for sorting, but apparently you can even pass a sort descriptor for a binary attribute without throwing an exception. The entity - store mismatch is the only thing I can think of right now but there are probably more.

**Comment by Revolucent** [comment]
@patgoley 

Well, the rationale behind removing `try` isn't that CDQI is so safe that there can be no errors. It's that any errors a developer is likely to get are errors that could only occur in the development cycle. If you screw up a sort descriptor, omit an entity, create an invalid predicate, misconfigure Core Data, etc., your program is simply invalid and will never ship.

If you can think of _any_ error likely to be encountered by CDQI that could realistically be "rescued" at runtime _in a shipping app_, then I will revert the `try` change. I can't think of one.

**Comment by patgoley** [comment]
@Revolucent You're right about that. In reality, someone could just use PredicateBuilder and bypass all of the type safety if they want to, which is fine, they're opting for it. We can just try! internally and they'll get the Core Data error, which would crash their app anyway. I can't think of any recoverable errors with  fetch requests; either it's valid or it's not.

**Comment by patgoley** [comment]
@Revolucent  I also removed all references to try! in the README on my branch, just so you know.

**Comment by Revolucent** [comment]
@patgoley I've also modified the README, but not to do that. Still, `git merge` is a marvelous thing.
