### ISSUE TITLE
Update the Example app for v4.0

### ISSUE THREAD

**Issue by Revolucent** [Prosumma/CoreDataQueryInterface#37]

**Comment by patgoley** [comment]
@Revolucent Example app is compiling again. Were you hoping to add anything to the app or just get it working with the 4.0 changes?

**Comment by Revolucent** [comment]
@patgoley I just wanted to get it compiling. That's pretty much it.

Note that I want to get v4.0 out the door by Monday. That's the goal. Unfortunately I will have little time to devote to it until this weekend. I have a couple of deliverables for tomorrow and will be very busy on Friday. Integrating v4.0 into my production codebases for my clients is a high priority for me next week, so I want an "official" release out. If the documentation and README aren't quite there yet, I'm happy to bump those to a point release, but I think the code itself is ready to ship, don't you?

**Comment by patgoley** [comment]
@Revolucent I think the code is good to go. Totally cool with bumping the readme and docs until later.

**Comment by Revolucent** [comment]
@patgoley Actually, I'm going to release v4.0 sometime late this afternoon or evening EST. The milestone I'm calling v4.1 will become v4.2. I'll release v4.1 sometime next week, and it will have the updated documentation and README.

Note that the README has been updated. I just think it needs some more polish.
