### ISSUE TITLE
cdqi script not included in cocoapods install

### ISSUE THREAD

**Issue by patgoley** [Prosumma/CoreDataQueryInterface#51]
I was attempting a Cocoapods install (only to figure out where the cdqi script would be located for reference) and realized it's not actually included in the podspec. Looking at the podspec documentation, I don't see anything for including files that aren't built and included in the Pods library. I'm not sure how we get around that, but it seems like a fatal flaw for cocoapods users.

**Comment by Revolucent** [comment]
I'm not sure it's fatal. I imagine most CocoaPods users are proficient enough to be able to get the `cdqi` script from Github. But it _is_ a pain in the butt for them, and ideally we want it to come down the pipe.

I'll look into it. (And I certainly won't object if you do as well. Hint, hint.)

**Comment by Revolucent** [comment]
A preliminary survey of the options available to a Podspec author does not look promising. As an alternative, we could provide a link directly in the Github README to download the `cdqi` tool.

**Comment by patgoley** [comment]
@Revolucent  Would it make sense to list cdqi as a gem so it could be easily installed separately? On one hand, your project won't compile unless you have the CoreDataQueryInterface.framework in your project, so it isn't totally stand alone, but it would provide an easy route to install for cocoapod users.

**Comment by Revolucent** [comment]
Not a bad idea, since it's just a simple Ruby executable. Never done a gem before, but I can't imagine it's rocket science. Let me give it a little thought. I'm a little busy early this week, so I won't be able to get to any of this for a bit.

This will add yet another step to the releas process for CDQI. That's fine, but I need to draw up some kind of release document for my own use so I don't forget a step: Make sure "Top Hits" runs, increment build number, fix up CocoaPods, take a short nap, etc.

**Comment by patgoley** [comment]
Hey @Revolucent long time no chat! I'm knocking around with the latest version of CDQI on a toy project and I ran into this issue again. I'd be happy to figure out the whole gem thing if you'd like to move forward here. It seems like the only other option for pod users is to include the file as a resource of the pod, but that just feels wrong to me.

**Comment by Revolucent** [comment]
@patgoley What do you think of the idea of creating another project for the `cdqi` command line tool. I would create it as a part of my organization, but I would make you the maintainer. This might be a more convenient way to turn it into a gem.
