### ISSUE TITLE
Example projects should be built in Travis

### ISSUE THREAD

**Issue by patgoley** [Prosumma/CoreDataQueryInterface#52]
Currently the example project is not validated in the Travis build. I haven't used Travis much so I'm not sure where to put it it but I think the command we need is something like:

```
xcodebuild -project /Examples/TopHits/TopHits.xcodeproj -scheme TopHits -sdk $SDK -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
```

**Comment by Revolucent** [comment]
I agree. I think it's important to build the CDQI iOS scheme in as many configurations as possible. However, for the example project, I'd prefer just a sanity check. Travis takes long enough as it is, and sometimes it times out and I have to run it (or one of the builds) over again. So I don't want to tax it too much.
