### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by EvgeniyGT** [Prosumma/CoreDataQueryInterface#56]
What about Swift 3 support?

**Comment by Revolucent** [comment]
Take a look at the [CDQI v5 branch](https://github.com/Prosumma/CoreDataQueryInterface/tree/cdqi5). It is not complete and may not compile with the current Swift 3, but thanks for reminding me that I need to get this out the door soon. I will make it a priority this weekend.

**Comment by Revolucent** [comment]
I am hard at work on this. At the moment I'm converting the unit tests to Swift 3 and trying to get everything to work.

**Comment by patgoley** [comment]
Hey there @Revolucent! I was just checking out the v5 branch and it looks pretty solid. Anything else you were hoping to get done before merging? Just wondering if I can help out.

**Comment by Revolucent** [comment]
@patgoley I completely missed this! Yes, I could have used your help, actually.
