### ISSUE TITLE
Fix Swift 4 Warnings

### ISSUE THREAD

**Issue by patgoley** [Prosumma/CoreDataQueryInterface#58]
No breaking changes for Swift 4, only a few warnings that certain generic constraints were redundant. For example, if you declare `func query<M: NSManagedObject>() -> Query<M, M>`, the `M: NSManagedObject` is redundant since it's already required by Query. I've fixed these warnings on my fork. Probably don't want to merge to master until Xcode 9 release, but perhaps just publish the branch on the main repository so it's available? For those of us who are OCD about project warnings hah.

**Comment by Revolucent** [comment]
Yes, I noticed that myself. I'll create a `swift4` branch and fix this stuff. Sound good?

**Comment by patgoley** [comment]
Sure thing! It's not much work but I do have the warnings fixed on my branch in case you want to just push that up. 

https://github.com/patgoley/CoreDataQueryInterface/tree/swift-4

**Comment by Revolucent** [comment]
I'll just use yours and then close this issue. Thanks again!

**Comment by Revolucent** [comment]
It may be a little while. I have to download Xcode 9 again for reasons too boring to get into.
