### ISSUE TITLE
Don't include date in generated file comment header, maybe a hash instead?

### ISSUE THREAD

**Issue by patgoley** [Prosumma/CoreDataQueryInterface#59]
Including the date in the generated files causes unnecessary changes in git when run automatically. I'm not sure that the date of generation is important, really only the model version it was generated from. Perhaps a hash of the model itself would be more appropriate? Sorry, I know this is really picky, but I think CDQI is best used in automation (run script phase or CI), and I keep having to commit or reset model files that have changes only because it's a new day. Happy to implement it myself, just let me know what you think.

**Comment by invoy-ghigley** [comment]
Sounds great to me! If you make this change, I will commit it.

**Comment by Revolucent** [comment]
Sounds great to me. If you submit a pull request, I will integrate it.

**Comment by Revolucent** [comment]
Maybe we don't even need the hash.

**Comment by patgoley** [comment]
On second thought, you're right. The changes to the model class itself are enough to know that it's changed. No need for a secondary indicator.
